fix: detect workspace package manager
stackblitz-labs/pkg.pr.new pull request #130
Opened 2024-07-02 09:10 UTC by AmirSa12

2024-07-02 09:48 UTC, AmirSa12 commented
resolves #129

2024-07-05 06:54 UTC, Aslemammad commented on packages/cli/index.ts
> +import { detectPackageManager } from "../backend/server/utils/markdown";
why is it in markdown utils? I don't think it should be there, let's have it inlined in this file!

2024-07-05 20:18 UTC, Aslemammad requested changes
Good progress!

2024-07-05 20:18 UTC, Aslemammad commented on packages/backend/server/routes/publish.post.ts
> +  const packageManager = packageManagerHeader || detectPackageManager(".");
This is the server, how would we detect the user's packageManager from the server?

2024-07-05 20:18 UTC, Aslemammad commented on packages/backend/server/routes/publish.post.ts
> +function detectPackageManager(rootPath: string): "npm" | "pnpm" {
This should be in the cli and not in the server!

2024-07-05 20:18 UTC, Aslemammad commented on packages/backend/server/utils/markdown.ts
> +${packageManager} ${packageManager === "npm" ? "i" : "add"} ${refUrl}
let's just put `i` for both npm and pnpm

2024-07-05 20:18 UTC, Aslemammad commented on packages/cli/index.ts
> +          function detectPackageManager(rootPath: string): "npm" | "pnpm" {
put this method at the end of the file! like other methods.

2024-07-08 16:20 UTC, Aslemammad requested changes
Amazing progress! love it.

2024-07-08 16:20 UTC, Aslemammad commented on packages/cli/index.ts
> +function detectPackageManager(rootPath: string): "npm" | "pnpm" {
let's use what @sadeghbarati suggested or detect package manager by egoist!

2024-07-08 16:20 UTC, Aslemammad commented on packages/backend/server/utils/markdown.ts
> +${packageManager} ${packageManager === "npm" ? "i" : "add"} ${shaUrl}
let's have an object like this

```
{
npm: "i",
pnpm: "add",
yarn: "add"
```
and then based on what the package manager is, we choose!

2024-07-08 16:20 UTC, Aslemammad commented on packages/backend/server/routes/publish.post.ts
> +  const packageManager = packageManagerHeader || "npm";
let's have a package manager of type PackageManager with possible values (npm, pnpm and yarn)

2024-07-08 16:28 UTC, Aslemammad commented on package.json
> +    "detect-package-manager": "^3.0.2",
We have to put it in cli package json, not here!

2024-07-08 19:44 UTC, Aslemammad requested changes

2024-07-08 19:44 UTC, Aslemammad commented on packages/backend/server/utils/markdown.ts
> +const packageCommands: Record<string, string> = {
`Record<PackageManager, string>`

2024-07-08 19:44 UTC, Aslemammad commented on packages/backend/server/utils/markdown.ts
> +  packageManager: string,
Let's use `PackageManager` type here!

2024-07-08 19:44 UTC, Aslemammad commented on packages/backend/server/utils/markdown.ts
> +  packageManager: string,
same here!

2024-07-08 19:44 UTC, Aslemammad commented on packages/cli/index.ts
> +          const detectPackageManager = detect();
just await, no need for `.then`

2024-07-08 19:44 UTC, Aslemammad commented on packages/cli/index.ts
> +// function detectPackageManager(rootPath: string): "npm" | "pnpm" {
Let's remove these comments!

2024-07-08 19:44 UTC, Aslemammad commented on packages/backend/server/routes/publish.post.ts
> +import type { PackageManager } from "@pkg-pr-new/utils";
If this type is only used in this file, then let's inline it here and remove it from utils!

2024-07-08 20:01 UTC, Aslemammad requested changes

2024-07-08 20:01 UTC, Aslemammad commented on packages/cli/index.ts
> +          const detectPackageManager = detect();
just const packageManager = await detect() is enough

2024-07-08 20:14 UTC, Aslemammad approved these changes

2024-07-08 20:15 UTC, merged

2024-07-08 20:15 UTC, Aslemammad commented
Thank you so much for the hard work!