chore: add docs for --json usage
stackblitz-labs/pkg.pr.new pull request #262
Opened 2024-10-10 19:41 UTC by AmirSa12

2024-10-10 20:43 UTC, AmirSa12 commented
seems like its working

2024-10-10 21:11 UTC, Aslemammad commented
The commit mentioned in that message is wrong!

2024-10-11 19:24 UTC, Aslemammad requested changes
Good progress!

2024-10-11 19:24 UTC, Aslemammad commented on .github/workflows/ci.yml
> +      - name: Post or update comment
Ok, now let's remove this and I'll merge!

2024-10-11 19:24 UTC, Aslemammad commented on README.md
> +## Custom GitHub Messages and Comments
Put this section after the 2 examples of yaml files we already have.

2024-10-11 20:25 UTC, AmirSa12 commented
resolves: #252 #253 #260

2024-10-12 04:39 UTC, Aslemammad requested changes

2024-10-12 04:39 UTC, Aslemammad commented on README.md
>  > Releasing approved pull requests is the recommended way of having continuous releases. This ensures users always install approved and safe packages.
This should be above the new example! Because it talks about the examples we had above!

2024-10-12 04:39 UTC, Aslemammad commented on README.md
> +name: Publish packages
This is not valid github workflow yml, update it please. See how we do it.

2024-10-12 05:31 UTC, Aslemammad approved these changes

2024-10-12 05:32 UTC, merged

2024-10-12 06:27 UTC, David-Pena commented
Thank you so much for the great examples and details 🙏🏻🔥 @AmirSa12